name: Continuous Delivery

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore TwoSum.sln

      - name: Build
        run: dotnet build TwoSum.sln --no-restore --configuration Release

      - name: Publish application
        run: dotnet publish TwoSum.sln -c Release -o ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: projetozipado
          path: ./publish/**

  deploy:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: projetozipado
          path: ./app

      - name: Show downloaded files
        run: ls -R ./app
